# Generated by Django 4.1.3 on 2022-11-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
