# Generated by Django 4.1.3 on 2022-12-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_information_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='user',
        ),
        migrations.AddField(
            model_name='voting',
            name='chat_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
