# Generated by Django 4.1.3 on 2022-12-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_voting_user_voting_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='vote',
        ),
        migrations.AddField(
            model_name='voting',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.information'),
        ),
    ]
