# Generated by Django 4.1.3 on 2023-01-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_voting_vote_voting_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
