# Generated by Django 4.1.3 on 2023-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_information_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
